name: PR
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create string
        run: |
          MY_STRING=$(cat << EOF
| --- a.json-original	2021-01-07 23:03:55.107563000 +0000
| +++ a.json-migrated	2021-01-07 23:03:55.106563000 +0000
| @@ -4,7 +4,7 @@
|           "postUpdateOptions": ["yarnDedupeHighest"],
|           "rangeStrategy": "replace",
|           "rebaseWhen": "behind-base-branch",
| -         "semanticCommits": true,
| +         "semanticCommits": "enabled",
|           "updateLockFiles": true,
|           "prConcurrentLimit": 0,
|           "prHourlyLimit": 0,
| --- ux.json-original	2021-01-07 23:04:03.068103000 +0000
| +++ ux.json-migrated	2021-01-07 23:04:03.067103000 +0000
| @@ -4,7 +4,7 @@
|           "postUpdateOptions": ["yarnDedupeHighest"],
|           "rangeStrategy": "replace",
|           "rebaseWhen": "behind-base-branch",
| -         "semanticCommits": true,
| +         "semanticCommits": "enabled",
|           "updateLockFiles": true,
|           "prConcurrentLimit": 0,
|           "prHourlyLimit": 0,
          EOF
          )
          echo "MY_STRING<<EOF" >> $GITHUB_ENV
          echo "$MY_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ env.MY_STRING }}"

