name: PR
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create string
        run: |
          cat - > diffoutput.txt << EOF
           --- a.json-original	2021-01-07 23:03:55.107563000 +0000
           +++ a.json-migrated	2021-01-07 23:03:55.106563000 +0000
           @@ -4,7 +4,7 @@
                     "postUpdateOptions": ["yarnDedupeHighest"],
                     "rangeStrategy": "replace",
                     "rebaseWhen": "behind-base-branch",
           -         "semanticCommits": true,
           +         "semanticCommits": "enabled",
                     "updateLockFiles": true,
                     "prConcurrentLimit": 0,
                     "prHourlyLimit": 0,
          EOF
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: diffoutput.txt
